<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Association Registration</title>
</head>
<body>
    <h2>New Association Registration</h2>
    
    <p>Hello Admin,</p>
    
    <p>A new association has registered:</p>
    
    <p>You can take appropriate action to manage the association's registration.</p>
    
    <p>Regards,<br>
    SKI AND SNOWBOARD INDIA</p>
    
    <p>This is an autogenerated email.</p>
</body>
</html>
